"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import api.openapi_client
from gr4vy_api.openapi_client.model.user import User
globals()['User'] = User
from gr4vy_api.openapi_client.model.users import Users


class TestUsers(unittest.TestCase):
    """Users unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsers(self):
        """Test Users"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Users()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
