"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class APIRoutersAPIKeyPairsSchemasCreatorTypedDict(TypedDict):
    id: str
    r"""The ID of the user or API key pair that created the API key pair."""
    name: str
    r"""The name of the user or API key pair that created the API key pair."""
    email_address: NotRequired[Nullable[str]]
    r"""The email address of the user that created the API key pair, when it was created by a dashboard user."""
    thumbprint: NotRequired[Nullable[str]]
    r"""The thumbprint of the API key pair that created the API key pair, when it was created by another API key."""


class APIRoutersAPIKeyPairsSchemasCreator(BaseModel):
    id: str
    r"""The ID of the user or API key pair that created the API key pair."""

    name: str
    r"""The name of the user or API key pair that created the API key pair."""

    email_address: OptionalNullable[str] = UNSET
    r"""The email address of the user that created the API key pair, when it was created by a dashboard user."""

    thumbprint: OptionalNullable[str] = UNSET
    r"""The thumbprint of the API key pair that created the API key pair, when it was created by another API key."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["email_address", "thumbprint"])
        nullable_fields = set(["email_address", "thumbprint"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
