"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from gr4vy.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class APICommonSchemasMerchantAccountTypedDict(TypedDict):
    id: str
    display_name: str
    created_at: datetime
    updated_at: datetime
    type: Literal["merchant-account"]
    over_capture_amount: NotRequired[Nullable[int]]
    over_capture_percentage: NotRequired[Nullable[int]]


class APICommonSchemasMerchantAccount(BaseModel):
    id: str

    display_name: str

    created_at: datetime

    updated_at: datetime

    TYPE: Annotated[
        Annotated[
            Optional[Literal["merchant-account"]],
            AfterValidator(validate_const("merchant-account")),
        ],
        pydantic.Field(alias="type"),
    ] = "merchant-account"

    over_capture_amount: OptionalNullable[int] = UNSET

    over_capture_percentage: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["type", "over_capture_amount", "over_capture_percentage"]
        )
        nullable_fields = set(["over_capture_amount", "over_capture_percentage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    APICommonSchemasMerchantAccount.model_rebuild()
except NameError:
    pass
