"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .certificatealgorithm import CertificateAlgorithm
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class APIKeyPairCreateTypedDict(TypedDict):
    display_name: str
    r"""The display name for the API key pair."""
    role_ids: List[str]
    r"""The ID of the role to assign to the API key pair. Exactly one role is supported. The caller can only assign a role whose scopes are a subset of its own."""
    algorithm: NotRequired[CertificateAlgorithm]
    active: NotRequired[bool]
    r"""Whether the API key pair should be active and usable once created."""
    merchant_account_ids: NotRequired[List[str]]
    r"""The IDs of the merchant accounts to associate with the API key pair. An empty list grants access to all merchant accounts. The caller can only assign merchant accounts it has access to."""
    public_key: NotRequired[Nullable[str]]
    r"""A PEM-encoded ECDSA P-521 (ES512) public key. Provide this to register your own key pair (bring your own key); If omitted, Gr4vy will generate the key pair and return the private key."""


class APIKeyPairCreate(BaseModel):
    display_name: str
    r"""The display name for the API key pair."""

    role_ids: List[str]
    r"""The ID of the role to assign to the API key pair. Exactly one role is supported. The caller can only assign a role whose scopes are a subset of its own."""

    algorithm: Optional[CertificateAlgorithm] = None

    active: Optional[bool] = True
    r"""Whether the API key pair should be active and usable once created."""

    merchant_account_ids: Optional[List[str]] = None
    r"""The IDs of the merchant accounts to associate with the API key pair. An empty list grants access to all merchant accounts. The caller can only assign merchant accounts it has access to."""

    public_key: OptionalNullable[str] = UNSET
    r"""A PEM-encoded ECDSA P-521 (ES512) public key. Provide this to register your own key pair (bring your own key); If omitted, Gr4vy will generate the key pair and return the private key."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["algorithm", "active", "merchant_account_ids", "public_key"]
        )
        nullable_fields = set(["public_key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
