"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class APIKeyPairUpdateTypedDict(TypedDict):
    display_name: NotRequired[Nullable[str]]
    r"""The display name for the API key pair."""
    active: NotRequired[Nullable[bool]]
    r"""Whether the API key pair is active and can be used to authenticate."""
    role_ids: NotRequired[Nullable[List[str]]]
    merchant_account_ids: NotRequired[Nullable[List[str]]]
    r"""The IDs of the merchant accounts to associate with the API key pair. The caller can only assign merchant accounts it has access to."""


class APIKeyPairUpdate(BaseModel):
    display_name: OptionalNullable[str] = UNSET
    r"""The display name for the API key pair."""

    active: OptionalNullable[bool] = UNSET
    r"""Whether the API key pair is active and can be used to authenticate."""

    role_ids: OptionalNullable[List[str]] = UNSET

    merchant_account_ids: OptionalNullable[List[str]] = UNSET
    r"""The IDs of the merchant accounts to associate with the API key pair. The caller can only assign merchant accounts it has access to."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["display_name", "active", "role_ids", "merchant_account_ids"]
        )
        nullable_fields = set(
            ["display_name", "active", "role_ids", "merchant_account_ids"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
