"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class BankAccountHolderTypedDict(TypedDict):
    first_name: NotRequired[Nullable[str]]
    r"""The account holder's first name"""
    last_name: NotRequired[Nullable[str]]
    r"""The account holder's last name"""
    company_name: NotRequired[Nullable[str]]
    r"""The account holder's company name"""


class BankAccountHolder(BaseModel):
    first_name: OptionalNullable[str] = UNSET
    r"""The account holder's first name"""

    last_name: OptionalNullable[str] = UNSET
    r"""The account holder's last name"""

    company_name: OptionalNullable[str] = UNSET
    r"""The account holder's company name"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["first_name", "last_name", "company_name"])
        nullable_fields = set(["first_name", "last_name", "company_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
