"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .braintreedynamicdatafieldsoptions import (
    BraintreeDynamicDataFieldsOptions,
    BraintreeDynamicDataFieldsOptionsTypedDict,
)
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict
from typing_extensions import NotRequired, TypedDict


class BraintreeOptionsTypedDict(TypedDict):
    discount_amount: NotRequired[Nullable[int]]
    r"""Passes a discount amount to be applied to the transaction when using Braintree."""
    custom_fields: NotRequired[Nullable[Dict[str, str]]]
    r"""Passes `customFields` to the Braintree API when creating a new payment. Custom fields allow you to customize your checkout experience by collecting specific information about your customers and their purchases."""
    dynamic_data_fields: NotRequired[
        Nullable[BraintreeDynamicDataFieldsOptionsTypedDict]
    ]
    r"""Additional dynamic fields to pass to the Braintree API"""


class BraintreeOptions(BaseModel):
    discount_amount: OptionalNullable[int] = UNSET
    r"""Passes a discount amount to be applied to the transaction when using Braintree."""

    custom_fields: OptionalNullable[Dict[str, str]] = UNSET
    r"""Passes `customFields` to the Braintree API when creating a new payment. Custom fields allow you to customize your checkout experience by collecting specific information about your customers and their purchases."""

    dynamic_data_fields: OptionalNullable[BraintreeDynamicDataFieldsOptions] = UNSET
    r"""Additional dynamic fields to pass to the Braintree API"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["discount_amount", "custom_fields", "dynamic_data_fields"]
        )
        nullable_fields = set(
            ["discount_amount", "custom_fields", "dynamic_data_fields"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
