"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .billingdetails import BillingDetails, BillingDetailsTypedDict
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class BuyerCreateTypedDict(TypedDict):
    r"""Request body for creating a new buyer"""

    display_name: NotRequired[Nullable[str]]
    r"""The display name for the buyer."""
    external_identifier: NotRequired[Nullable[str]]
    r"""The merchant identifier for this buyer."""
    billing_details: NotRequired[Nullable[BillingDetailsTypedDict]]
    r"""The billing name, address, email, and other fields for this buyer."""
    account_number: NotRequired[Nullable[str]]
    r"""The buyer account number"""


class BuyerCreate(BaseModel):
    r"""Request body for creating a new buyer"""

    display_name: OptionalNullable[str] = UNSET
    r"""The display name for the buyer."""

    external_identifier: OptionalNullable[str] = UNSET
    r"""The merchant identifier for this buyer."""

    billing_details: OptionalNullable[BillingDetails] = UNSET
    r"""The billing name, address, email, and other fields for this buyer."""

    account_number: OptionalNullable[str] = UNSET
    r"""The buyer account number"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["display_name", "external_identifier", "billing_details", "account_number"]
        )
        nullable_fields = set(
            ["display_name", "external_identifier", "billing_details", "account_number"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
