"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class CardScheme(str, Enum, metaclass=utils.OpenEnumMeta):
    ACCEL = "accel"
    AMEX = "amex"
    BANCONTACT = "bancontact"
    CARTE_BANCAIRE = "carte-bancaire"
    CIRRUS = "cirrus"
    CULIANCE = "culiance"
    DANKORT = "dankort"
    DINERS_CLUB = "diners-club"
    DISCOVER = "discover"
    EFTPOS_AUSTRALIA = "eftpos-australia"
    ELO = "elo"
    HIPERCARD = "hipercard"
    JCB = "jcb"
    MAESTRO = "maestro"
    MASTERCARD = "mastercard"
    MIR = "mir"
    NYCE = "nyce"
    OTHER = "other"
    PULSE = "pulse"
    RUPAY = "rupay"
    STAR = "star"
    UATP = "uatp"
    UNIONPAY = "unionpay"
    VISA = "visa"
