"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ChaseOptionsTypedDict(TypedDict):
    comments: NotRequired[Nullable[str]]
    r"""Custom order comment"""


class ChaseOptions(BaseModel):
    comments: OptionalNullable[str] = UNSET
    r"""Custom order comment"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["comments"])
        nullable_fields = set(["comments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
