"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cardtype import CardType
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class CheckoutSessionPaymentMethodDetailsTypedDict(TypedDict):
    bin: NotRequired[Nullable[str]]
    r"""The first 6 digit of the card."""
    card_country: NotRequired[Nullable[str]]
    r"""The country of the card issuer."""
    card_type: NotRequired[Nullable[CardType]]
    r"""The payment scheme of the card."""
    card_issuer_name: NotRequired[Nullable[str]]
    r"""The card issuer."""


class CheckoutSessionPaymentMethodDetails(BaseModel):
    bin: OptionalNullable[str] = UNSET
    r"""The first 6 digit of the card."""

    card_country: OptionalNullable[str] = UNSET
    r"""The country of the card issuer."""

    card_type: OptionalNullable[CardType] = UNSET
    r"""The payment scheme of the card."""

    card_issuer_name: OptionalNullable[str] = UNSET
    r"""The card issuer."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bin", "card_country", "card_type", "card_issuer_name"])
        nullable_fields = set(["bin", "card_country", "card_type", "card_issuer_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
