"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pazemobilesession import PazeMobileSession, PazeMobileSessionTypedDict
from .pazesessionrequest import PazeSessionRequest, PazeSessionRequestTypedDict
from .pazewebsession import PazeWebSession, PazeWebSessionTypedDict
from gr4vy.types import BaseModel, UNSET_SENTINEL
from gr4vy.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class CreatePazeDigitalWalletSessionGlobalsTypedDict(TypedDict):
    merchant_account_id: NotRequired[str]
    r"""The ID of the merchant account to use for this request."""


class CreatePazeDigitalWalletSessionGlobals(BaseModel):
    merchant_account_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-gr4vy-merchant-account-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of the merchant account to use for this request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["merchant_account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreatePazeDigitalWalletSessionRequestTypedDict(TypedDict):
    paze_session_request: PazeSessionRequestTypedDict
    merchant_account_id: NotRequired[str]
    r"""The ID of the merchant account to use for this request."""


class CreatePazeDigitalWalletSessionRequest(BaseModel):
    paze_session_request: Annotated[
        PazeSessionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    merchant_account_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-gr4vy-merchant-account-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of the merchant account to use for this request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["merchant_account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ResponseCreatePazeDigitalWalletSessionTypedDict = TypeAliasType(
    "ResponseCreatePazeDigitalWalletSessionTypedDict",
    Union[PazeWebSessionTypedDict, PazeMobileSessionTypedDict],
)
r"""Successful Response"""


ResponseCreatePazeDigitalWalletSession = TypeAliasType(
    "ResponseCreatePazeDigitalWalletSession", Union[PazeWebSession, PazeMobileSession]
)
r"""Successful Response"""
