"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .digitalwalletprovider import DigitalWalletProvider
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DigitalWalletCreateTypedDict(TypedDict):
    r"""Request body for registering a new digital wallet"""

    provider: DigitalWalletProvider
    merchant_name: str
    accept_terms_and_conditions: bool
    merchant_display_name: NotRequired[Nullable[str]]
    merchant_url: NotRequired[Nullable[str]]
    merchant_country_code: NotRequired[Nullable[str]]
    domain_names: NotRequired[List[str]]


class DigitalWalletCreate(BaseModel):
    r"""Request body for registering a new digital wallet"""

    provider: DigitalWalletProvider

    merchant_name: str

    accept_terms_and_conditions: bool

    merchant_display_name: OptionalNullable[str] = UNSET

    merchant_url: OptionalNullable[str] = UNSET

    merchant_country_code: OptionalNullable[str] = UNSET

    domain_names: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "merchant_display_name",
                "merchant_url",
                "merchant_country_code",
                "domain_names",
            ]
        )
        nullable_fields = set(
            ["merchant_display_name", "merchant_url", "merchant_country_code"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
