"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict


DlocalPIXSubscriptionAmountOptionsType = Union[
    Literal[
        "FIXED",
        "VARIABLE",
    ],
    UnrecognizedStr,
]
r"""Indicates the amount type unit for the subscription. Allowed values are: `FIXED`, `VARIABLE`."""


class DlocalPIXSubscriptionAmountOptionsTypedDict(TypedDict):
    type: DlocalPIXSubscriptionAmountOptionsType
    r"""Indicates the amount type unit for the subscription. Allowed values are: `FIXED`, `VARIABLE`."""
    min_value: Nullable[str]
    r"""Minimum payer enrollment limit, not minimum recurring charge amount."""
    value: NotRequired[Nullable[str]]
    r"""Fixed subscription amount in local currency. Required only for fixed amount subscriptions depending on the payment method."""


class DlocalPIXSubscriptionAmountOptions(BaseModel):
    type: DlocalPIXSubscriptionAmountOptionsType
    r"""Indicates the amount type unit for the subscription. Allowed values are: `FIXED`, `VARIABLE`."""

    min_value: Nullable[str]
    r"""Minimum payer enrollment limit, not minimum recurring charge amount."""

    value: OptionalNullable[str] = UNSET
    r"""Fixed subscription amount in local currency. Required only for fixed amount subscriptions depending on the payment method."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["value"])
        nullable_fields = set(["value", "min_value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
