"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class DlocalCardOptionsTypedDict(TypedDict):
    three_dsecure_force: NotRequired[Nullable[bool]]
    r"""Indicates whether to force dlocal hosted 3D Secure authentication for the card transaction."""


class DlocalCardOptions(BaseModel):
    three_dsecure_force: OptionalNullable[bool] = UNSET
    r"""Indicates whether to force dlocal hosted 3D Secure authentication for the card transaction."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["three_dsecure_force"])
        nullable_fields = set(["three_dsecure_force"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
