"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel
from typing_extensions import TypedDict


class GenericModelTypedDict(TypedDict):
    pass


class GenericModel(BaseModel):
    pass
