"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .giftcardservice import GiftCardService, GiftCardServiceTypedDict
from datetime import datetime
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from gr4vy.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GiftCardIssuanceTypedDict(TypedDict):
    id: str
    r"""The ID for the gift card issuance."""
    merchant_account_id: str
    r"""The ID of the merchant account this gift card issuance belongs to."""
    gift_card_service: GiftCardServiceTypedDict
    gift_card_service_payment_issuance_id: str
    r"""The identifier for this issuance as provided by the gift card service."""
    url: str
    r"""The URL for the issued gift card."""
    amount: int
    r"""The amount loaded onto the gift card, in the smallest denomination for the currency."""
    currency: str
    r"""The ISO-4217 currency code for the `amount`."""
    created_at: datetime
    r"""The date and time when this gift card was issued."""
    updated_at: datetime
    r"""The date and time when this gift card issuance was last updated."""
    type: Literal["gift-card-issuance"]
    r"""Always `gift-card-issuance`."""
    external_identifier: NotRequired[Nullable[str]]
    r"""The external identifier provided when issuing the gift card."""


class GiftCardIssuance(BaseModel):
    id: str
    r"""The ID for the gift card issuance."""

    merchant_account_id: str
    r"""The ID of the merchant account this gift card issuance belongs to."""

    gift_card_service: GiftCardService

    gift_card_service_payment_issuance_id: str
    r"""The identifier for this issuance as provided by the gift card service."""

    url: str
    r"""The URL for the issued gift card."""

    amount: int
    r"""The amount loaded onto the gift card, in the smallest denomination for the currency."""

    currency: str
    r"""The ISO-4217 currency code for the `amount`."""

    created_at: datetime
    r"""The date and time when this gift card was issued."""

    updated_at: datetime
    r"""The date and time when this gift card issuance was last updated."""

    TYPE: Annotated[
        Annotated[
            Optional[Literal["gift-card-issuance"]],
            AfterValidator(validate_const("gift-card-issuance")),
        ],
        pydantic.Field(alias="type"),
    ] = "gift-card-issuance"
    r"""Always `gift-card-issuance`."""

    external_identifier: OptionalNullable[str] = UNSET
    r"""The external identifier provided when issuing the gift card."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "external_identifier"])
        nullable_fields = set(["external_identifier"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GiftCardIssuance.model_rebuild()
except NameError:
    pass
