"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class GiftCardServiceProvider(str, Enum, metaclass=utils.OpenEnumMeta):
    MOCK_GIFT_CARD = "mock-gift-card"
    QWIKCILVER_GIFT_CARD = "qwikcilver-gift-card"
