"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .giftcardserviceprovider import GiftCardServiceProvider
from gr4vy.types import BaseModel, UNSET_SENTINEL
from gr4vy.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class GiftCardServiceTypedDict(TypedDict):
    id: str
    r"""The ID for the gift card service."""
    gift_card_service_definition_id: GiftCardServiceProvider
    display_name: str
    r"""The display name for the gift card service."""
    type: Literal["gift-card-service"]
    r"""Always `gift-card-service`."""


class GiftCardService(BaseModel):
    id: str
    r"""The ID for the gift card service."""

    gift_card_service_definition_id: GiftCardServiceProvider

    display_name: str
    r"""The display name for the gift card service."""

    TYPE: Annotated[
        Annotated[
            Optional[Literal["gift-card-service"]],
            AfterValidator(validate_const("gift-card-service")),
        ],
        pydantic.Field(alias="type"),
    ] = "gift-card-service"
    r"""Always `gift-card-service`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GiftCardService.model_rebuild()
except NameError:
    pass
