"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class GiftCardRedemptionStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    CREATED = "created"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    SKIPPED = "skipped"
