"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class InstrumentType(str, Enum, metaclass=utils.OpenEnumMeta):
    PAN = "pan"
    CARD_TOKEN = "card_token"
    REDIRECT = "redirect"
    REDIRECT_TOKEN = "redirect_token"
    GOOGLEPAY = "googlepay"
    APPLEPAY = "applepay"
    NETWORK_TOKEN = "network_token"
