"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .klarnasubscriptionoptions import (
    KlarnaSubscriptionOptions,
    KlarnaSubscriptionOptionsTypedDict,
)
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class KlarnaOptionsTypedDict(TypedDict):
    subscription: NotRequired[Nullable[KlarnaSubscriptionOptionsTypedDict]]
    r"""Provides subscription information to Klarna."""
    token_only_mode: NotRequired[Nullable[bool]]
    r"""When set to `true`, this will authorize the transaction with Klarna for the purposes of tokenizing the payment method with the transaction details. No funds will be captured and the authorization will be automatically voided. This is useful for up-sell scenarios where you want to tokenize a Klarna payment method for future use."""
    authorization_token: NotRequired[Nullable[str]]
    r"""An authorization token returned by the Klarna Express Checkout JS SDK after the buyer completes payment in the embedded widget. When provided, the connector skips the HPP redirect and places the Klarna order directly using this token."""


class KlarnaOptions(BaseModel):
    subscription: OptionalNullable[KlarnaSubscriptionOptions] = UNSET
    r"""Provides subscription information to Klarna."""

    token_only_mode: OptionalNullable[bool] = UNSET
    r"""When set to `true`, this will authorize the transaction with Klarna for the purposes of tokenizing the payment method with the transaction details. No funds will be captured and the authorization will be automatically voided. This is useful for up-sell scenarios where you want to tokenize a Klarna payment method for future use."""

    authorization_token: OptionalNullable[str] = UNSET
    r"""An authorization token returned by the Klarna Express Checkout JS SDK after the buyer completes payment in the embedded widget. When provided, the connector skips the HPP redirect and places the Klarna order directly using this token."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["subscription", "token_only_mode", "authorization_token"]
        )
        nullable_fields = set(
            ["subscription", "token_only_mode", "authorization_token"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
