"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


Interval = Union[
    Literal[
        "DAY",
        "WEEK",
        "MONTH",
        "YEAR",
    ],
    UnrecognizedStr,
]
r"""The cadence unit for the subscription plan."""


class KlarnaSubscriptionOptionsTypedDict(TypedDict):
    name: str
    r"""The name of the subscription product. The recommended format includes a subscription id and double curly brackets."""
    interval: Interval
    r"""The cadence unit for the subscription plan."""
    interval_count: int
    r"""The number corresponding to the interval unit."""
    reference: str
    r"""Reference to a SKU in the transaction's cart items to link subscription to."""


class KlarnaSubscriptionOptions(BaseModel):
    name: str
    r"""The name of the subscription product. The recommended format includes a subscription id and double curly brackets."""

    interval: Interval
    r"""The cadence unit for the subscription plan."""

    interval_count: int
    r"""The number corresponding to the interval unit."""

    reference: str
    r"""Reference to a SKU in the transaction's cart items to link subscription to."""
