"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class MockCardMerchantAdviceCodeOptionsTypedDict(TypedDict):
    account_number: Nullable[str]
    r"""When set, the MAC is only returned if the card number matches this account number."""
    result: NotRequired[Nullable[str]]
    r"""The MAC to return for this request."""


class MockCardMerchantAdviceCodeOptions(BaseModel):
    account_number: Nullable[str]
    r"""When set, the MAC is only returned if the card number matches this account number."""

    result: OptionalNullable[str] = UNSET
    r"""The MAC to return for this request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["result"])
        nullable_fields = set(["result", "account_number"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
