"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mockcardmerchantadvicecodeoptions import (
    MockCardMerchantAdviceCodeOptions,
    MockCardMerchantAdviceCodeOptionsTypedDict,
)
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class MockCardOptionsTypedDict(TypedDict):
    merchant_advice_code: NotRequired[
        Nullable[MockCardMerchantAdviceCodeOptionsTypedDict]
    ]
    r"""Allows for mocking the merchant advice code."""
    skip_retry: NotRequired[Nullable[bool]]
    r"""When set to true, prevents retries on failed transactions."""


class MockCardOptions(BaseModel):
    merchant_advice_code: OptionalNullable[MockCardMerchantAdviceCodeOptions] = UNSET
    r"""Allows for mocking the merchant advice code."""

    skip_retry: OptionalNullable[bool] = UNSET
    r"""When set to true, prevents retries on failed transactions."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["merchant_advice_code", "skip_retry"])
        nullable_fields = set(["merchant_advice_code", "skip_retry"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
