"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class NuveiAirlineDataOptionsTypedDict(TypedDict):
    seat_class: NotRequired[Nullable[str]]
    r"""The seat class of the booking"""
    is_cardholder_traveling: NotRequired[Nullable[bool]]
    r"""Indicates whether the cardholder is also a passenger."""


class NuveiAirlineDataOptions(BaseModel):
    seat_class: Annotated[OptionalNullable[str], pydantic.Field(alias="seatClass")] = (
        UNSET
    )
    r"""The seat class of the booking"""

    is_cardholder_traveling: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isCardholderTraveling")
    ] = UNSET
    r"""Indicates whether the cardholder is also a passenger."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["seatClass", "isCardholderTraveling"])
        nullable_fields = set(["seatClass", "isCardholderTraveling"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    NuveiAirlineDataOptions.model_rebuild()
except NameError:
    pass
