"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class NuveiIDealOptionsTypedDict(TypedDict):
    custom_data: NotRequired[Nullable[str]]
    r"""Additional data to be sent to Nuvei."""


class NuveiIDealOptions(BaseModel):
    custom_data: Annotated[
        OptionalNullable[str], pydantic.Field(alias="customData")
    ] = UNSET
    r"""Additional data to be sent to Nuvei."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["customData"])
        nullable_fields = set(["customData"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
