"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cardscheme import CardScheme
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from gr4vy.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PaymentMethodCardTypedDict(TypedDict):
    number: str
    r"""The 13-19 digit number for this card as it can be found on the front of the card."""
    expiration_date: str
    r"""The expiration date of the card, formatted `MM/YY`."""
    method: Literal["card"]
    r"""Set to `card` to use a new card."""
    card_scheme: NotRequired[Nullable[CardScheme]]
    r"""The optional card's network scheme."""
    external_identifier: NotRequired[Nullable[str]]
    r"""The merchant identifier for this card."""


class PaymentMethodCard(BaseModel):
    number: str
    r"""The 13-19 digit number for this card as it can be found on the front of the card."""

    expiration_date: str
    r"""The expiration date of the card, formatted `MM/YY`."""

    METHOD: Annotated[
        Annotated[Optional[Literal["card"]], AfterValidator(validate_const("card"))],
        pydantic.Field(alias="method"),
    ] = "card"
    r"""Set to `card` to use a new card."""

    card_scheme: OptionalNullable[CardScheme] = UNSET
    r"""The optional card's network scheme."""

    external_identifier: OptionalNullable[str] = UNSET
    r"""The merchant identifier for this card."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["method", "card_scheme", "external_identifier"])
        nullable_fields = set(["card_scheme", "external_identifier"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PaymentMethodCard.model_rebuild()
except NameError:
    pass
