"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address import Address, AddressTypedDict
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from gr4vy.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PayoutMerchantSummaryTypedDict(TypedDict):
    r"""PayoutMerchantSummary

    Represents a summary of a merchant.
    """

    name: str
    r"""The name of the merchant."""
    identification_number: str
    r"""Unique value which identifies a merchant for processing transactions, also known as a MID."""
    phone_number: str
    r"""The phone number for the merchant which should be formatted according to the E164 number standard."""
    url: str
    r"""Merchant website URL."""
    merchant_category_code: str
    r"""Merchant classification for the type of goods or services it provides."""
    type: Literal["merchant"]
    r"""Always `merchant`."""
    statement_descriptor: NotRequired[Nullable[str]]
    r"""Value to explain charges or payments on bank statements."""
    address: NotRequired[Nullable[AddressTypedDict]]
    r"""The address for the merchant."""


class PayoutMerchantSummary(BaseModel):
    r"""PayoutMerchantSummary

    Represents a summary of a merchant.
    """

    name: str
    r"""The name of the merchant."""

    identification_number: str
    r"""Unique value which identifies a merchant for processing transactions, also known as a MID."""

    phone_number: str
    r"""The phone number for the merchant which should be formatted according to the E164 number standard."""

    url: str
    r"""Merchant website URL."""

    merchant_category_code: str
    r"""Merchant classification for the type of goods or services it provides."""

    TYPE: Annotated[
        Annotated[
            Optional[Literal["merchant"]], AfterValidator(validate_const("merchant"))
        ],
        pydantic.Field(alias="type"),
    ] = "merchant"
    r"""Always `merchant`."""

    statement_descriptor: OptionalNullable[str] = UNSET
    r"""Value to explain charges or payments on bank statements."""

    address: OptionalNullable[Address] = UNSET
    r"""The address for the merchant."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "statement_descriptor", "address"])
        nullable_fields = set(["statement_descriptor", "address"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
