"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class PayoutStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    DECLINED = "declined"
    FAILED = "failed"
    PENDING = "pending"
    SUCCEEDED = "succeeded"
