"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import NotRequired, TypedDict


CallbackEvent = Union[
    Literal[
        "SHIPPING_ADDRESS",
        "SHIPPING_OPTIONS",
    ],
    UnrecognizedStr,
]


class PaypalOrderUpdateCallbackConfigTypedDict(TypedDict):
    callback_url: NotRequired[Nullable[str]]
    r"""The URL for the webhook endpoint you provide for PayPal to send you order update events."""
    callback_events: NotRequired[Nullable[List[CallbackEvent]]]
    r"""The events that trigger a callback."""


class PaypalOrderUpdateCallbackConfig(BaseModel):
    callback_url: OptionalNullable[str] = UNSET
    r"""The URL for the webhook endpoint you provide for PayPal to send you order update events."""

    callback_events: OptionalNullable[List[CallbackEvent]] = UNSET
    r"""The events that trigger a callback."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["callback_url", "callback_events"])
        nullable_fields = set(["callback_url", "callback_events"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
