"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class PazeTransactionValueTypedDict(TypedDict):
    transaction_currency: str
    r"""ISO 4217 currency code of the transaction."""
    transaction_amount: str
    r"""Amount of the transaction including dollar and cents, e.g. '99.95'."""


class PazeTransactionValue(BaseModel):
    transaction_currency: Annotated[str, pydantic.Field(alias="transactionCurrency")]
    r"""ISO 4217 currency code of the transaction."""

    transaction_amount: Annotated[str, pydantic.Field(alias="transactionAmount")]
    r"""Amount of the transaction including dollar and cents, e.g. '99.95'."""


try:
    PazeTransactionValue.model_rebuild()
except NameError:
    pass
