"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class PazeBillingAddressTypedDict(TypedDict):
    name: Nullable[str]
    r"""Name of the organization or entity at the address."""
    line1: str
    r"""Line 1 of the address."""
    line2: Nullable[str]
    r"""Line 2 of the address."""
    line3: Nullable[str]
    r"""Line 3 of the address."""
    city: str
    r"""City."""
    state: str
    r"""State or region."""
    zip: str
    r"""Postal code."""
    country_code: Nullable[str]
    r"""ISO 3166-1 alpha-2 country code."""


class PazeBillingAddress(BaseModel):
    name: Nullable[str]
    r"""Name of the organization or entity at the address."""

    line1: str
    r"""Line 1 of the address."""

    line2: Nullable[str]
    r"""Line 2 of the address."""

    line3: Nullable[str]
    r"""Line 3 of the address."""

    city: str
    r"""City."""

    state: str
    r"""State or region."""

    zip: str
    r"""Postal code."""

    country_code: Annotated[Nullable[str], pydantic.Field(alias="countryCode")]
    r"""ISO 3166-1 alpha-2 country code."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    PazeBillingAddress.model_rebuild()
except NameError:
    pass
