"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pazemobilenumber import PazeMobileNumber, PazeMobileNumberTypedDict
from gr4vy.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class PazeDeliveryContactDetailsTypedDict(TypedDict):
    contact_full_name: Nullable[str]
    r"""Consumer-provided name of the contact person."""
    contact_phone_number: Nullable[PazeMobileNumberTypedDict]


class PazeDeliveryContactDetails(BaseModel):
    contact_full_name: Annotated[Nullable[str], pydantic.Field(alias="contactFullName")]
    r"""Consumer-provided name of the contact person."""

    contact_phone_number: Annotated[
        Nullable[PazeMobileNumber], pydantic.Field(alias="contactPhoneNumber")
    ]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    PazeDeliveryContactDetails.model_rebuild()
except NameError:
    pass
