"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class PazeMobileSessionCreateTypedDict(TypedDict):
    paze_checkout_url: str
    r"""Session URL for launching the Paze checkout UI from the native mobile app."""
    client_context: str
    r"""Merchant-defined transaction identifier echoed from the request."""
    ew_sid: str
    r"""Globally unique session identifier generated by Paze."""
    timestamp_iso8601: str
    r"""Timestamp when the response was sent by Paze, in ISO 8601 format."""


class PazeMobileSessionCreate(BaseModel):
    paze_checkout_url: Annotated[str, pydantic.Field(alias="pazeCheckoutUrl")]
    r"""Session URL for launching the Paze checkout UI from the native mobile app."""

    client_context: Annotated[str, pydantic.Field(alias="clientContext")]
    r"""Merchant-defined transaction identifier echoed from the request."""

    ew_sid: Annotated[str, pydantic.Field(alias="ewSID")]
    r"""Globally unique session identifier generated by Paze."""

    timestamp_iso8601: Annotated[str, pydantic.Field(alias="timestampISO8601")]
    r"""Timestamp when the response was sent by Paze, in ISO 8601 format."""


try:
    PazeMobileSessionCreate.model_rebuild()
except NameError:
    pass
