"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class PazeSessionCompleteTypedDict(TypedDict):
    payload_id: str
    r"""Unique identifier generated by Paze to track and link the wallet transaction. Used as the wallet transaction identifier."""
    complete_response: Nullable[str]
    r"""Opaque token returned by Paze for the completion call."""
    secure_payload: Nullable[str]
    r"""Signed and encrypted payload containing the data necessary to process the payment. Returned when `payloadTypeIndicator` is PAYMENT."""
    client_context: str
    r"""Echo of the `clientContext` sent on the request. Returned by Paze for client-side tracing."""
    ew_sid: str
    r"""Paze-issued session identifier returned for tracing."""
    timestamp_iso8601: str
    r"""Server timestamp of the Paze response in ISO 8601 format. Returned for tracing."""


class PazeSessionComplete(BaseModel):
    payload_id: Annotated[str, pydantic.Field(alias="payloadId")]
    r"""Unique identifier generated by Paze to track and link the wallet transaction. Used as the wallet transaction identifier."""

    complete_response: Annotated[
        Nullable[str], pydantic.Field(alias="completeResponse")
    ]
    r"""Opaque token returned by Paze for the completion call."""

    secure_payload: Annotated[Nullable[str], pydantic.Field(alias="securePayload")]
    r"""Signed and encrypted payload containing the data necessary to process the payment. Returned when `payloadTypeIndicator` is PAYMENT."""

    client_context: Annotated[str, pydantic.Field(alias="clientContext")]
    r"""Echo of the `clientContext` sent on the request. Returned by Paze for client-side tracing."""

    ew_sid: Annotated[str, pydantic.Field(alias="ewSID")]
    r"""Paze-issued session identifier returned for tracing."""

    timestamp_iso8601: Annotated[str, pydantic.Field(alias="timestampISO8601")]
    r"""Server timestamp of the Paze response in ISO 8601 format. Returned for tracing."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    PazeSessionComplete.model_rebuild()
except NameError:
    pass
