"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class PazeCobrandItemTypedDict(TypedDict):
    name: str
    r"""Product name of the cobrand card. Must match exactly with the card name from the network."""
    benefits_offered: NotRequired[Nullable[bool]]
    r"""Whether benefits are offered for this cobrand card."""


class PazeCobrandItem(BaseModel):
    name: str
    r"""Product name of the cobrand card. Must match exactly with the card name from the network."""

    benefits_offered: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="benefitsOffered")
    ] = UNSET
    r"""Whether benefits are offered for this cobrand card."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["benefitsOffered"])
        nullable_fields = set(["benefitsOffered"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PazeCobrandItem.model_rebuild()
except NameError:
    pass
