"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class PazeClientTypedDict(TypedDict):
    id: str
    r"""Client identifier generated by Paze and shared during onboarding."""
    name: NotRequired[Nullable[str]]
    r"""Display name associated with the client for presentation purposes."""
    profile_id: NotRequired[Nullable[str]]
    r"""Client profile to use during checkout."""


class PazeClient(BaseModel):
    id: str
    r"""Client identifier generated by Paze and shared during onboarding."""

    name: OptionalNullable[str] = UNSET
    r"""Display name associated with the client for presentation purposes."""

    profile_id: Annotated[OptionalNullable[str], pydantic.Field(alias="profileId")] = (
        UNSET
    )
    r"""Client profile to use during checkout."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "profileId"])
        nullable_fields = set(["name", "profileId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PazeClient.model_rebuild()
except NameError:
    pass
