"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class PazeSessionReviewRequestTypedDict(TypedDict):
    session_id: str
    r"""Session reference identifier generated by the merchant. Must match the value sent in the Paze session create call."""
    code: str
    r"""Opaque token issued by the Paze service in the response from the most recent Paze UX interaction (checkout, change card, or change shipping address)."""
    access_token: str
    r"""The Paze OAuth access token returned by the Paze mobile session create call. Used to authenticate the request to Paze."""


class PazeSessionReviewRequest(BaseModel):
    session_id: Annotated[str, pydantic.Field(alias="sessionId")]
    r"""Session reference identifier generated by the merchant. Must match the value sent in the Paze session create call."""

    code: str
    r"""Opaque token issued by the Paze service in the response from the most recent Paze UX interaction (checkout, change card, or change shipping address)."""

    access_token: Annotated[str, pydantic.Field(alias="accessToken")]
    r"""The Paze OAuth access token returned by the Paze mobile session create call. Used to authenticate the request to Paze."""


try:
    PazeSessionReviewRequest.model_rebuild()
except NameError:
    pass
