"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pazeenhancedtransactiondata import (
    PazeEnhancedTransactionData,
    PazeEnhancedTransactionDataTypedDict,
)
from .pazetransactionoptions import (
    PazeTransactionOptions,
    PazeTransactionOptionsTypedDict,
)
from .pazetransactionvalue import PazeTransactionValue, PazeTransactionValueTypedDict
from gr4vy.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
import pydantic
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import Annotated, NotRequired, TypedDict


PazeSessionCompleteRequestTransactiontype = Union[
    Literal[
        "PURCHASE",
        "CARD_ON_FILE",
        "BOTH",
    ],
    UnrecognizedStr,
]
r"""The type of transaction being completed. PURCHASE for a one-off checkout, CARD_ON_FILE to retain the card for future use, or BOTH."""


ProcessingNetwork = Union[
    Literal[
        "VISA",
        "MASTERCARD",
        "DISCOVER",
    ],
    UnrecognizedStr,
]


class PazeSessionCompleteRequestTypedDict(TypedDict):
    session_id: str
    r"""Session reference identifier generated by the merchant. Must match the value sent in the Paze session create call."""
    code: str
    r"""Opaque token issued by the Paze service in the response from the most recent Paze UX interaction."""
    access_token: str
    r"""The Paze OAuth access token returned by the Paze mobile session create call. Used to authenticate the request to Paze."""
    transaction_type: PazeSessionCompleteRequestTransactiontype
    r"""The type of transaction being completed. PURCHASE for a one-off checkout, CARD_ON_FILE to retain the card for future use, or BOTH."""
    transaction_options: NotRequired[Nullable[PazeTransactionOptionsTypedDict]]
    r"""Client configuration data overriding values configured during merchant onboarding."""
    transaction_value: NotRequired[Nullable[PazeTransactionValueTypedDict]]
    r"""Required when `transactionType` is PURCHASE or BOTH. Must be omitted when `transactionType` is CARD_ON_FILE."""
    processing_network: NotRequired[Nullable[ProcessingNetwork]]
    r"""Card network to process the transaction on. If not provided, Paze defaults to the network on the front of the card."""
    enhanced_transaction_data: NotRequired[
        Nullable[PazeEnhancedTransactionDataTypedDict]
    ]
    r"""Additional purchase context used by Paze for risk scoring."""


class PazeSessionCompleteRequest(BaseModel):
    session_id: Annotated[str, pydantic.Field(alias="sessionId")]
    r"""Session reference identifier generated by the merchant. Must match the value sent in the Paze session create call."""

    code: str
    r"""Opaque token issued by the Paze service in the response from the most recent Paze UX interaction."""

    access_token: Annotated[str, pydantic.Field(alias="accessToken")]
    r"""The Paze OAuth access token returned by the Paze mobile session create call. Used to authenticate the request to Paze."""

    transaction_type: Annotated[
        PazeSessionCompleteRequestTransactiontype,
        pydantic.Field(alias="transactionType"),
    ]
    r"""The type of transaction being completed. PURCHASE for a one-off checkout, CARD_ON_FILE to retain the card for future use, or BOTH."""

    transaction_options: Annotated[
        OptionalNullable[PazeTransactionOptions],
        pydantic.Field(alias="transactionOptions"),
    ] = UNSET
    r"""Client configuration data overriding values configured during merchant onboarding."""

    transaction_value: Annotated[
        OptionalNullable[PazeTransactionValue], pydantic.Field(alias="transactionValue")
    ] = UNSET
    r"""Required when `transactionType` is PURCHASE or BOTH. Must be omitted when `transactionType` is CARD_ON_FILE."""

    processing_network: Annotated[
        OptionalNullable[ProcessingNetwork], pydantic.Field(alias="processingNetwork")
    ] = UNSET
    r"""Card network to process the transaction on. If not provided, Paze defaults to the network on the front of the card."""

    enhanced_transaction_data: Annotated[
        OptionalNullable[PazeEnhancedTransactionData],
        pydantic.Field(alias="enhancedTransactionData"),
    ] = UNSET
    r"""Additional purchase context used by Paze for risk scoring."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "transactionOptions",
                "transactionValue",
                "processingNetwork",
                "enhancedTransactionData",
            ]
        )
        nullable_fields = set(
            [
                "transactionOptions",
                "transactionValue",
                "processingNetwork",
                "enhancedTransactionData",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PazeSessionCompleteRequest.model_rebuild()
except NameError:
    pass
