"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pazeecomdata import PazeEcomData, PazeEcomDataTypedDict
from .pazetraveldata import PazeTravelData, PazeTravelDataTypedDict
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class PazeEnhancedTransactionDataTypedDict(TypedDict):
    ecom_data: NotRequired[Nullable[PazeEcomDataTypedDict]]
    r"""Details pertaining to electronic commerce purchases."""
    travel_data: NotRequired[Nullable[PazeTravelDataTypedDict]]
    r"""Details pertaining to travel bookings."""


class PazeEnhancedTransactionData(BaseModel):
    ecom_data: Annotated[
        OptionalNullable[PazeEcomData], pydantic.Field(alias="ecomData")
    ] = UNSET
    r"""Details pertaining to electronic commerce purchases."""

    travel_data: Annotated[
        OptionalNullable[PazeTravelData], pydantic.Field(alias="travelData")
    ] = UNSET
    r"""Details pertaining to travel bookings."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ecomData", "travelData"])
        nullable_fields = set(["ecomData", "travelData"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PazeEnhancedTransactionData.model_rebuild()
except NameError:
    pass
