"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class PazeWebSessionTypedDict(TypedDict):
    id: str
    r"""The Paze merchant data ID."""
    name: str
    r"""The merchant display name."""
    profile_id: str
    r"""The Paze profile ID for the given domain."""


class PazeWebSession(BaseModel):
    id: str
    r"""The Paze merchant data ID."""

    name: str
    r"""The merchant display name."""

    profile_id: Annotated[str, pydantic.Field(alias="profileId")]
    r"""The Paze profile ID for the given domain."""


try:
    PazeWebSession.model_rebuild()
except NameError:
    pass
