"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pazeclient import PazeClient, PazeClientTypedDict
from .pazecobranditem import PazeCobrandItem, PazeCobrandItemTypedDict
from .pazetransactionvalue import PazeTransactionValue, PazeTransactionValueTypedDict
from gr4vy.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Intent = Union[
    Literal[
        "REVIEW_AND_PAY",
        "EXPRESS_CHECKOUT",
        "ADD_CARD",
    ],
    UnrecognizedStr,
]
r"""Primary intent of the checkout session."""


TransactionType = Union[
    Literal[
        "PURCHASE",
        "CARD_ON_FILE",
        "BOTH",
    ],
    UnrecognizedStr,
]


ShippingPreference = Union[
    Literal[
        "ALL",
        "NONE",
    ],
    UnrecognizedStr,
]


BillingPreference = Union[
    Literal[
        "ALL",
        "ZIP_COUNTRY",
        "NONE",
    ],
    UnrecognizedStr,
]


AcceptedPaymentCardNetwork = Union[
    Literal[
        "VISA",
        "MASTERCARD",
    ],
    UnrecognizedStr,
]


class PazeMobileSessionCreateRequestTypedDict(TypedDict):
    client: PazeClientTypedDict
    session_id: str
    r"""Session reference identifier generated by the merchant. Must be reused across all Paze APIs in a checkout session."""
    access_token: str
    r"""Access token obtained from the Paze session endpoint with source=mobile."""
    callback_url_scheme: str
    r"""Merchant app's ID (iOS bundle identifier or Android application ID) used as the callback URL scheme."""
    intent: Intent
    r"""Primary intent of the checkout session."""
    transaction_value: NotRequired[Nullable[PazeTransactionValueTypedDict]]
    r"""Currency and amount of the transaction. Required when intent is EXPRESS_CHECKOUT."""
    transaction_type: NotRequired[Nullable[TransactionType]]
    r"""Type of transaction."""
    shipping_preference: NotRequired[Nullable[ShippingPreference]]
    r"""Whether to collect a shipping address from the consumer."""
    billing_preference: NotRequired[Nullable[BillingPreference]]
    r"""Verbosity of billing address required."""
    email_address: NotRequired[Nullable[str]]
    r"""Consumer email address for checkout flow optimization."""
    phone_number: NotRequired[Nullable[str]]
    r"""Consumer phone number for checkout flow optimization."""
    cobrand: NotRequired[Nullable[List[PazeCobrandItemTypedDict]]]
    r"""Details for cobranded cards offered by the merchant."""
    accepted_shipping_countries: NotRequired[Nullable[List[str]]]
    r"""ISO 3166-1 alpha-2 country codes restricting eligible shipping addresses. Empty list or absence means all countries accepted."""
    accepted_payment_card_networks: NotRequired[
        Nullable[List[AcceptedPaymentCardNetwork]]
    ]
    r"""Accepted payment card networks. Empty list or absence means all networks accepted."""
    always_enable_checkout: NotRequired[bool]
    r"""Set to true to enable Paze checkout even if the provided email address or phone number does not match a Paze wallet."""


class PazeMobileSessionCreateRequest(BaseModel):
    client: PazeClient

    session_id: Annotated[str, pydantic.Field(alias="sessionId")]
    r"""Session reference identifier generated by the merchant. Must be reused across all Paze APIs in a checkout session."""

    access_token: Annotated[str, pydantic.Field(alias="accessToken")]
    r"""Access token obtained from the Paze session endpoint with source=mobile."""

    callback_url_scheme: Annotated[str, pydantic.Field(alias="callbackURLScheme")]
    r"""Merchant app's ID (iOS bundle identifier or Android application ID) used as the callback URL scheme."""

    intent: Intent
    r"""Primary intent of the checkout session."""

    transaction_value: Annotated[
        OptionalNullable[PazeTransactionValue], pydantic.Field(alias="transactionValue")
    ] = UNSET
    r"""Currency and amount of the transaction. Required when intent is EXPRESS_CHECKOUT."""

    transaction_type: Annotated[
        OptionalNullable[TransactionType], pydantic.Field(alias="transactionType")
    ] = UNSET
    r"""Type of transaction."""

    shipping_preference: Annotated[
        OptionalNullable[ShippingPreference], pydantic.Field(alias="shippingPreference")
    ] = UNSET
    r"""Whether to collect a shipping address from the consumer."""

    billing_preference: Annotated[
        OptionalNullable[BillingPreference], pydantic.Field(alias="billingPreference")
    ] = UNSET
    r"""Verbosity of billing address required."""

    email_address: Annotated[
        OptionalNullable[str], pydantic.Field(alias="emailAddress")
    ] = UNSET
    r"""Consumer email address for checkout flow optimization."""

    phone_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="phoneNumber")
    ] = UNSET
    r"""Consumer phone number for checkout flow optimization."""

    cobrand: OptionalNullable[List[PazeCobrandItem]] = UNSET
    r"""Details for cobranded cards offered by the merchant."""

    accepted_shipping_countries: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="acceptedShippingCountries")
    ] = UNSET
    r"""ISO 3166-1 alpha-2 country codes restricting eligible shipping addresses. Empty list or absence means all countries accepted."""

    accepted_payment_card_networks: Annotated[
        OptionalNullable[List[AcceptedPaymentCardNetwork]],
        pydantic.Field(alias="acceptedPaymentCardNetworks"),
    ] = UNSET
    r"""Accepted payment card networks. Empty list or absence means all networks accepted."""

    always_enable_checkout: Annotated[
        Optional[bool], pydantic.Field(alias="alwaysEnableCheckout")
    ] = False
    r"""Set to true to enable Paze checkout even if the provided email address or phone number does not match a Paze wallet."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "transactionValue",
                "transactionType",
                "shippingPreference",
                "billingPreference",
                "emailAddress",
                "phoneNumber",
                "cobrand",
                "acceptedShippingCountries",
                "acceptedPaymentCardNetworks",
                "alwaysEnableCheckout",
            ]
        )
        nullable_fields = set(
            [
                "transactionValue",
                "transactionType",
                "shippingPreference",
                "billingPreference",
                "emailAddress",
                "phoneNumber",
                "cobrand",
                "acceptedShippingCountries",
                "acceptedPaymentCardNetworks",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PazeMobileSessionCreateRequest.model_rebuild()
except NameError:
    pass
