"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PermissionSetTypedDict(TypedDict):
    r"""The permissions granted by a role."""

    allow: List[str]
    r"""The scopes granted by this role."""


class PermissionSet(BaseModel):
    r"""The permissions granted by a role."""

    allow: List[str]
    r"""The scopes granted by this role."""
