"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class ProductType(str, Enum, metaclass=utils.OpenEnumMeta):
    PHYSICAL = "physical"
    DISCOUNT = "discount"
    SHIPPING_FEE = "shipping_fee"
    SALES_TAX = "sales_tax"
    DIGITAL = "digital"
    GIFT_CARD = "gift_card"
    STORE_CREDIT = "store_credit"
    SURCHARGE = "surcharge"
