"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class RefundTargetType(str, Enum, metaclass=utils.OpenEnumMeta):
    PAYMENT_METHOD = "payment-method"
    GIFT_CARD_REDEMPTION = "gift-card-redemption"
