"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .refundsettlement import RefundSettlement, RefundSettlementTypedDict
from gr4vy.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class RefundSettlementsTypedDict(TypedDict):
    r"""A list of settlement records for the refunds on a transaction."""

    items: List[RefundSettlementTypedDict]
    r"""The list of refund settlement objects."""


class RefundSettlements(BaseModel):
    r"""A list of settlement records for the refunds on a transaction."""

    items: List[RefundSettlement]
    r"""The list of refund settlement objects."""
