"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .reportcreatortype import ReportCreatorType
from .reportexecutionsummary import (
    ReportExecutionSummary,
    ReportExecutionSummaryTypedDict,
)
from .reportschedule import ReportSchedule
from .reportspec import ReportSpec, ReportSpecTypedDict
from datetime import datetime
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from gr4vy.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ReportTypedDict(TypedDict):
    id: str
    r"""The unique ID for the report."""
    merchant_account_id: str
    r"""The merchant account ID this report belongs to."""
    name: str
    r"""The name of the report."""
    created_at: datetime
    r"""The date this report was created at."""
    updated_at: datetime
    r"""The date this report was last updated."""
    schedule: ReportSchedule
    schedule_enabled: bool
    r"""Whether the report schedule is enabled."""
    schedule_timezone: str
    r"""The timezone for the report schedule."""
    spec: ReportSpecTypedDict
    type: Literal["report"]
    r"""Always `report`."""
    creator_id: NotRequired[Nullable[str]]
    r"""The ID of the user who created the report."""
    creator_display_name: NotRequired[Nullable[str]]
    r"""The display name of the report creator."""
    creator_type: NotRequired[Nullable[ReportCreatorType]]
    r"""The type of the report creator."""
    next_execution_at: NotRequired[Nullable[datetime]]
    r"""The next scheduled execution time for the report."""
    description: NotRequired[Nullable[str]]
    r"""A description of the report."""
    latest_execution: NotRequired[Nullable[ReportExecutionSummaryTypedDict]]
    r"""The latest execution summary for the report."""


class Report(BaseModel):
    id: str
    r"""The unique ID for the report."""

    merchant_account_id: str
    r"""The merchant account ID this report belongs to."""

    name: str
    r"""The name of the report."""

    created_at: datetime
    r"""The date this report was created at."""

    updated_at: datetime
    r"""The date this report was last updated."""

    schedule: ReportSchedule

    schedule_enabled: bool
    r"""Whether the report schedule is enabled."""

    schedule_timezone: str
    r"""The timezone for the report schedule."""

    spec: ReportSpec

    TYPE: Annotated[
        Annotated[
            Optional[Literal["report"]], AfterValidator(validate_const("report"))
        ],
        pydantic.Field(alias="type"),
    ] = "report"
    r"""Always `report`."""

    creator_id: OptionalNullable[str] = UNSET
    r"""The ID of the user who created the report."""

    creator_display_name: OptionalNullable[str] = UNSET
    r"""The display name of the report creator."""

    creator_type: OptionalNullable[ReportCreatorType] = UNSET
    r"""The type of the report creator."""

    next_execution_at: OptionalNullable[datetime] = UNSET
    r"""The next scheduled execution time for the report."""

    description: OptionalNullable[str] = UNSET
    r"""A description of the report."""

    latest_execution: OptionalNullable[ReportExecutionSummary] = UNSET
    r"""The latest execution summary for the report."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "type",
                "creator_id",
                "creator_display_name",
                "creator_type",
                "next_execution_at",
                "description",
                "latest_execution",
            ]
        )
        nullable_fields = set(
            [
                "creator_id",
                "creator_display_name",
                "creator_type",
                "next_execution_at",
                "description",
                "latest_execution",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
