"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class RiskifiedAntiFraudOptionsShippingAddressTypedDict(TypedDict):
    r"""An additional shipping address to pass to the Riskified API.

    Field names follow Riskified's Address model rather than the Gr4vy address
    format, since these options are passed through to their API. The `country` sent
    to Riskified is derived from `country_code`.
    """

    id: str
    r"""Unique identifier for this address, referenced by `line_items[].shipping_address_id` and `shipping_lines[].shipping_address_id`."""
    first_name: NotRequired[Nullable[str]]
    r"""First name of the recipient at this address."""
    last_name: NotRequired[Nullable[str]]
    r"""Last name of the recipient at this address."""
    phone: NotRequired[Nullable[str]]
    r"""The phone number of the recipient at this address, which should be formatted according to the E164 number standard."""
    city: NotRequired[Nullable[str]]
    r"""The city for the address."""
    country_code: NotRequired[Nullable[str]]
    r"""The country for the address in ISO 3166 format. The country name sent to Riskified is derived from this value."""
    zip: NotRequired[Nullable[str]]
    r"""The postal code or zip code for the address."""
    province: NotRequired[Nullable[str]]
    r"""The state, county, or province for the address."""
    province_code: NotRequired[Nullable[str]]
    r"""The code of the state, county, or province for the address. Riskified expects the subdivision on its own, without the country prefix used by ISO 3166-2."""
    address1: NotRequired[Nullable[str]]
    r"""The first line of the address."""
    address2: NotRequired[Nullable[str]]
    r"""The second line of the address."""
    company: NotRequired[Nullable[str]]
    r"""The optional name of the company or organisation to add to the address."""


class RiskifiedAntiFraudOptionsShippingAddress(BaseModel):
    r"""An additional shipping address to pass to the Riskified API.

    Field names follow Riskified's Address model rather than the Gr4vy address
    format, since these options are passed through to their API. The `country` sent
    to Riskified is derived from `country_code`.
    """

    id: str
    r"""Unique identifier for this address, referenced by `line_items[].shipping_address_id` and `shipping_lines[].shipping_address_id`."""

    first_name: OptionalNullable[str] = UNSET
    r"""First name of the recipient at this address."""

    last_name: OptionalNullable[str] = UNSET
    r"""Last name of the recipient at this address."""

    phone: OptionalNullable[str] = UNSET
    r"""The phone number of the recipient at this address, which should be formatted according to the E164 number standard."""

    city: OptionalNullable[str] = UNSET
    r"""The city for the address."""

    country_code: OptionalNullable[str] = UNSET
    r"""The country for the address in ISO 3166 format. The country name sent to Riskified is derived from this value."""

    zip: OptionalNullable[str] = UNSET
    r"""The postal code or zip code for the address."""

    province: OptionalNullable[str] = UNSET
    r"""The state, county, or province for the address."""

    province_code: OptionalNullable[str] = UNSET
    r"""The code of the state, county, or province for the address. Riskified expects the subdivision on its own, without the country prefix used by ISO 3166-2."""

    address1: OptionalNullable[str] = UNSET
    r"""The first line of the address."""

    address2: OptionalNullable[str] = UNSET
    r"""The second line of the address."""

    company: OptionalNullable[str] = UNSET
    r"""The optional name of the company or organisation to add to the address."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "first_name",
                "last_name",
                "phone",
                "city",
                "country_code",
                "zip",
                "province",
                "province_code",
                "address1",
                "address2",
                "company",
            ]
        )
        nullable_fields = set(
            [
                "first_name",
                "last_name",
                "phone",
                "city",
                "country_code",
                "zip",
                "province",
                "province_code",
                "address1",
                "address2",
                "company",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
