"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class RyftCardOptionsTypedDict(TypedDict):
    sub_account_id: NotRequired[Nullable[str]]
    r"""Ryft linked sub-account ID, sent as the `Account` header."""
    platform_fee: NotRequired[Nullable[int]]
    r"""Platform Fee in the transaction currency's smallest unit. Sent as Ryft's `platformFee` field."""


class RyftCardOptions(BaseModel):
    sub_account_id: OptionalNullable[str] = UNSET
    r"""Ryft linked sub-account ID, sent as the `Account` header."""

    platform_fee: OptionalNullable[int] = UNSET
    r"""Platform Fee in the transaction currency's smallest unit. Sent as Ryft's `platformFee` field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sub_account_id", "platform_fee"])
        nullable_fields = set(["sub_account_id", "platform_fee"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
