"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ThreeDSecureV2TypedDict(TypedDict):
    version: str
    authentication_response: NotRequired[Nullable[str]]
    directory_response: NotRequired[Nullable[str]]
    directory_transaction_id: NotRequired[Nullable[str]]
    transaction_reason: NotRequired[Nullable[str]]
    cavv: NotRequired[Nullable[str]]
    eci: NotRequired[Nullable[str]]
    cardholder_info: NotRequired[Nullable[str]]


class ThreeDSecureV2(BaseModel):
    version: str

    authentication_response: OptionalNullable[str] = UNSET

    directory_response: OptionalNullable[str] = UNSET

    directory_transaction_id: OptionalNullable[str] = UNSET

    transaction_reason: OptionalNullable[str] = UNSET

    cavv: OptionalNullable[str] = UNSET

    eci: OptionalNullable[str] = UNSET

    cardholder_info: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "authentication_response",
                "directory_response",
                "directory_transaction_id",
                "transaction_reason",
                "cavv",
                "eci",
                "cardholder_info",
            ]
        )
        nullable_fields = set(
            [
                "authentication_response",
                "directory_response",
                "directory_transaction_id",
                "transaction_reason",
                "cavv",
                "eci",
                "cardholder_info",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
