"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedsecurescenariooutcomeauthentication import (
    ThreeDSecureScenarioOutcomeAuthentication,
    ThreeDSecureScenarioOutcomeAuthenticationTypedDict,
)
from .threedsecurescenariooutcomeresult import (
    ThreeDSecureScenarioOutcomeResult,
    ThreeDSecureScenarioOutcomeResultTypedDict,
)
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ThreeDSecureScenarioOutcomeTypedDict(TypedDict):
    version: str
    r"""The version of 3DS which will be simulated."""
    authentication: ThreeDSecureScenarioOutcomeAuthenticationTypedDict
    result: NotRequired[Nullable[ThreeDSecureScenarioOutcomeResultTypedDict]]
    r"""3DS result value. Required if authentication status is \"C\"."""


class ThreeDSecureScenarioOutcome(BaseModel):
    version: str
    r"""The version of 3DS which will be simulated."""

    authentication: ThreeDSecureScenarioOutcomeAuthentication

    result: OptionalNullable[ThreeDSecureScenarioOutcomeResult] = UNSET
    r"""3DS result value. Required if authentication status is \"C\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["result"])
        nullable_fields = set(["result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
