"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gr4vy import utils


class ThreeDSecureMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    CHALLENGE = "challenge"
    FRICTIONLESS = "frictionless"
