"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .travelhubcustomdata import TravelHubCustomData, TravelHubCustomDataTypedDict
from gr4vy.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class TravelhubOptionsTypedDict(TypedDict):
    custom_data: NotRequired[Nullable[List[TravelHubCustomDataTypedDict]]]
    r"""A list of `customData` to pass to the TravelHub API."""
    company_name: NotRequired[Nullable[str]]
    r"""Customer company name to pass to the TravelHub API."""


class TravelhubOptions(BaseModel):
    custom_data: Annotated[
        OptionalNullable[List[TravelHubCustomData]], pydantic.Field(alias="customData")
    ] = UNSET
    r"""A list of `customData` to pass to the TravelHub API."""

    company_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="companyName")
    ] = UNSET
    r"""Customer company name to pass to the TravelHub API."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["customData", "companyName"])
        nullable_fields = set(["customData", "companyName"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
