"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.checkout_sessions_api import CheckoutSessionsApi  # noqa: E501


class TestCheckoutSessionsApi(unittest.TestCase):
    """CheckoutSessionsApi unit test stubs"""

    def setUp(self):
        self.api = CheckoutSessionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_checkout_session(self):
        """Test case for add_checkout_session

        Create a new Checkout Session  # noqa: E501
        """
        pass

    def test_delete_checkout_session(self):
        """Test case for delete_checkout_session

        Delete a Checkout Session  # noqa: E501
        """
        pass

    def test_get_checkout_session(self):
        """Test case for get_checkout_session

        Get a Checkout Session  # noqa: E501
        """
        pass

    def test_update_checkout_session_fields(self):
        """Test case for update_checkout_session_fields

        Update a Checkout Session's Secure Fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
