"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.api_logs_api import APILogsApi  # noqa: E501


class TestAPILogsApi(unittest.TestCase):
    """APILogsApi unit test stubs"""

    def setUp(self):
        self.api = APILogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_api_logs(self):
        """Test case for list_api_logs

        List API error Logs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
