"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_option_approval_ui import PaymentOptionApprovalUI


class TestPaymentOptionApprovalUI(unittest.TestCase):
    """PaymentOptionApprovalUI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentOptionApprovalUI(self):
        """Test PaymentOptionApprovalUI"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentOptionApprovalUI()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
