"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_method_definition import PaymentMethodDefinition
globals()['PaymentMethodDefinition'] = PaymentMethodDefinition
from openapi_client.model.payment_method_definitions import PaymentMethodDefinitions


class TestPaymentMethodDefinitions(unittest.TestCase):
    """PaymentMethodDefinitions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethodDefinitions(self):
        """Test PaymentMethodDefinitions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentMethodDefinitions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
