"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.reports_api import ReportsApi  # noqa: E501


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_report(self):
        """Test case for add_report

        New report  # noqa: E501
        """
        pass

    def test_generate_download_url(self):
        """Test case for generate_download_url

        Generate the download URL of a report execution result  # noqa: E501
        """
        pass

    def test_get_report(self):
        """Test case for get_report

        Get report  # noqa: E501
        """
        pass

    def test_get_report_execution(self):
        """Test case for get_report_execution

        Get report execution  # noqa: E501
        """
        pass

    def test_list_all_report_executions(self):
        """Test case for list_all_report_executions

        List all report executions  # noqa: E501
        """
        pass

    def test_list_report_executions(self):
        """Test case for list_report_executions

        List executions for a report  # noqa: E501
        """
        pass

    def test_list_reports(self):
        """Test case for list_reports

        List reports  # noqa: E501
        """
        pass

    def test_update_report(self):
        """Test case for update_report

        Update report  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
