"""
    Gr4vy API

    Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.  # noqa: E501

    The version of the OpenAPI document: 1.1.0-beta
    Contact: code@gr4vy.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.card_rules_api import CardRulesApi  # noqa: E501


class TestCardRulesApi(unittest.TestCase):
    """CardRulesApi unit test stubs"""

    def setUp(self):
        self.api = CardRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_card_rule(self):
        """Test case for add_card_rule

        Create card rule  # noqa: E501
        """
        pass

    def test_delete_card_rule(self):
        """Test case for delete_card_rule

        Delete card rule  # noqa: E501
        """
        pass

    def test_get_card_rule(self):
        """Test case for get_card_rule

        Get card rule  # noqa: E501
        """
        pass

    def test_list_cards_rules(self):
        """Test case for list_cards_rules

        List card rules  # noqa: E501
        """
        pass

    def test_update_card_rule(self):
        """Test case for update_card_rule

        Update card rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
