name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    # “At 08:30 on every day-of-week from Monday through Friday.”
    - cron: 30 8 * * 1-5

jobs:
  test:
    runs-on: ubuntu-latest
    
    timeout-minutes: 3
    strategy:
      matrix:
        python:
          - 3.9
          - 3.10
          - 3.11
          - 3.12

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.3

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run linter
        run: |
          poetry run pylint -j=0 tests src  

      - name: Run tests
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          poetry run pytest tests

      - uses: hmarr/auto-approve-action@v4
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        with:
          github-token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

  merge:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: automerge
        name: automerge
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          MERGE_LABELS: ''
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_ERROR_FAIL: true
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: false
          UPDATE_METHOD: rebase